### ISSUE TITLE
Add option to only activate the plugin for specific characters

### ISSUE THREAD

**Issue by Lorentary** [CodePanter/another-bronzeman-mode#1]
I have multiple characters, but when this plugin is installed they ALL become bronze-men. 

Could you add and option so you would have to type in the name(s) of you bronzeman (bronzemen) in order for the plugin to activate?

Currently I find myself turning the plugin on/off a lot which is super annoying and mostly I forget to turn it on again and thus I miss item drops (I have multiple instances of RuneLite running at once but only one of them is a bronzeman)

**Comment by CodePanter** [comment]
I'm sorry, I missed the opening of this issue entirely, sorry for the delay. Regarding your problem, I did consider making it that way, but runelite in general suggests keeping all your settings login specific, and handling different accounts with separate settings files.
This is documented here, under "Playing with multiple accounts": https://github.com/runelite/runelite/wiki/General-Features
I hope this helps you work around this problem, as this will support separate settings for all plugins, not just the bronzeman plugin.
