### ISSUE TITLE
Sync bronzeman unlocks on multiple devices

### ISSUE THREAD

**Issue by namcsmd** [CodePanter/another-bronzeman-mode#10]
I play on desktop and laptop and the item unlocks are not synchronized when I switch devices. I am signed in to runelite on each device, so is there any way to sync the unlocks with my runelite account instead of storing them locally on each device? Some runelite plugins already do this, like loot tracker and tile markers.

**Comment by CodePanter** [comment]
Hello! Thank you for your suggestion!
I can definitely take a look at how hard it would be to implement this. Do you by chance know of any specific 'plugin hub' plugins that do this? These plugins work a bit differently, so it would help a lot to be able to draw inspiration form such a plugin.

**Comment by nmachen** [comment]
I am not aware of any plugin hub plugins that sync like this, which may be an indication that it isn't possible. But it'd be pretty neat if plugin hub plugins could send data to the online runelite account page https://runelite.net/account/home somehow

**Comment by yosley2100** [comment]
How would I go about accessing the unlock list in order to transfer them to a new device?

**Comment by CodePanter** [comment]
If you are on windows, you can find the unlock file here:
C:\Users\**<Your-windows-username>**\.runelite\profiles\rsprofile.**<A-unique-profile-key>**\another-bronzeman-mode-unlocks.txt

On a new device, runelite might assign a new unique profile key to your account; so I would suggest installing the plugin on this device, seeing where it created your new another-bronzeman-mode-unlocks.txt file, and replacing that with your old one.
