### ISSUE TITLE
Disable unlocks when entering LMS

### ISSUE THREAD

**Issue by Swennet** [CodePanter/another-bronzeman-mode#11]
I accidentally unlocked a ton of end game items by going into LMS. It would be nice if these wouldn't unlock while going in there.

On another note, I know it's possible to clear all unlocks, but is it possible to clear just the few items I unlocked in LMS?

**Comment by Swennet** [comment]
Should have done some digging first, but I figured out how to re-lock items. Just posting here in case anyone else has the same issue.

Go into your runelite profile directory at `C:\Users\{yourname}\.runelite\profiles\{youraccount}`. There should be a file called "another-bronzeman-mode-unlocks.txt". Open this file in a text editor like Notepad.

Then go to [https://www.osrsbox.com/tools/item-search/](https://www.osrsbox.com/tools/item-search/) and search for the items you want to re-lock. Find the ID in the table, and remove it from your "another-bronzeman-mode-unlocks.txt" file. Save and you're done!

**Comment by Swennet** [comment]
And... I'm stupid. The items unlocked in NMZ have different item IDs than the real versions. Locking this.

**Comment by CodePanter** [comment]
I'm terribly sorry for responding weeks after you commented this. I'm glad to see you found a work around, as well as figured out the items aren't actually unlocked, only the LMS versions (which aren't for sale on the GE). 

I do want to point out however that if you go into your collection log, go to the Bronzeman unlocks page and right click any of the items you have unlocked there, you will find a way to re-lock items there without the need for editing files manually.

You can also choose to hide untradable items from the bronzeman interface and unlock popups, which would include the LMS files, effectively preventing this kind of confusion later!

I hope this helps!
