### ISSUE TITLE
Lost Unlocks

### ISSUE THREAD

**Issue by raccoondad96** [CodePanter/another-bronzeman-mode#15]
Hello CodePanter,
I recently managed to lose my unlocks while switching player profiles on Runelite while playing my Bronzemanmode account. I was wondering if it is possible or you know of a way for me to manually add the unlocks I had back to the bronzeman account?

**Comment by CodePanter** [comment]
Closing this as I believe the unlock system having been reworked since then, and will be revamped more soon. I think we managed to resolve this through discord together, but if not, I'm sorry, and I might be thinking of someone else!
