### ISSUE TITLE
Not Compatible with RuneLite v1.10.20.3

### ISSUE THREAD

**Issue by Orrezon** [CodePanter/another-bronzeman-mode#16]
Seeing: 
<img width="262" alt="image" src="https://github.com/CodePanter/another-bronzeman-mode/assets/41313760/69bdf978-c9d0-4fe5-87b6-baed658e8a8b">

With the following RuneLite build:
<img width="168" alt="image" src="https://github.com/CodePanter/another-bronzeman-mode/assets/41313760/4dd01b9e-e498-46bc-a3a0-b0e7187ef672">

**Comment by CodePanter** [comment]
Hey there! Thank you very much for bringing this to my attention! I have since fixed the cause, and made a pull-request, so hopefully runelite will approve it soon!
The request: https://github.com/runelite/plugin-hub/pull/5435

**Comment by CodePanter** [comment]
@Orrezon The plugin is restored and once again available in the plugin hub. A runelite reboot should do the trick. Thanks again for raising the issue!

**Comment by Orrezon** [comment]
You're the best thank you so much for such an insanely fast turn around time! :)
