### ISSUE TITLE
Icon not showing in chat

### ISSUE THREAD

**Issue by PhantomFoxyRS** [CodePanter/another-bronzeman-mode#19]
The Bronzeman Icon shows next to my character; but doesn't show when I talk in public chat or clan chat. I attached screenshots of it not showing Bronzeman Icon in chat and my settings. Hopefully there's an easy fix for this
![Screenshot_47](https://github.com/user-attachments/assets/663407ff-c40a-455f-a566-f9b781763fdf)
![Screenshot_48](https://github.com/user-attachments/assets/e7ac1bbd-1d8a-4f16-a9f3-48bc2956b8cb)

**Comment by CodePanter** [comment]
Hey there! The names in the 'Bronzeman Names' field need to be comma separated, otherwise it treats it as one big name. 
So in your case, it should be: 
Phantom Foxy,Shiny Roiru

I hope this helps!

**Comment by PhantomFoxyRS** [comment]
Unfortunately it's still not showing the icon in clan chat. It shows in Friend chat no problem. First image is from Friend Chat; second from Clan Chat
![Screenshot_49](https://github.com/user-attachments/assets/53405f2d-9b67-401d-84d5-f75801d4e0aa)
![Screenshot_50](https://github.com/user-attachments/assets/ed2306c0-4327-4c53-ac16-d9248f8edb88)

**Comment by CodePanter** [comment]
Interesting, I hadn't noticed this yet myself, but after checking in-game, you appear to be right. I'll try and see if I can fix look into it this weekend!

**Comment by CodePanter** [comment]
This has been fixed, and will be available in the game as soon as the pull request for the plugin hub is accepted here:
https://github.com/runelite/plugin-hub/pull/6302

**Comment by CodePanter** [comment]
This fix is now live in the plugin hub. Thanks again for reporting this!
