### ISSUE TITLE
Collection log feature broken

### ISSUE THREAD

**Issue by Hannah-GBS** [CodePanter/another-bronzeman-mode#2]
It doesn't show up in the list any more. I'd assume this is because of the recent collection log update Jagex did.

**Comment by CodePanter** [comment]
First up, thank you for notifying me! I'm sorry for the late reply, it seems I don't get a notification when someone creates an issue. With a bit of luck, this will be fixed later today!

**Comment by CodePanter** [comment]
I managed to fix this yesterday and this new version was accepted in the plugin hub about an hour ago. I also added a setting for 'moving' the bronzeman unlocks to the 'Other' tab, which was previously the default behaviour. When this setting is off, you will see your bronzeman unlocks as soon as you open the collection log.
