### ISSUE TITLE
Logged in after couple of months break and all the unlocks are gone.

### ISSUE THREAD

**Issue by RuunArmee** [CodePanter/another-bronzeman-mode#22]
Heya! I was wondering what has happened, have had some breaks before aswell, but it has never happened before. I logged in, checked unlocks, there wasn't even "Bronzeman unlocks" available... I am afraid to turn it on and off again, because then it will surely reset it all.

Is there anything I could do? If I go to profiles on runelite and find my bronzeman file, there are "another-bronzeman-mode-unlocks.txt" file still there, but for some reason it doesn't translate over into the game.

Got any suggestions?

Thanks!

**Comment by CodePanter** [comment]
If the file is still there, we can surely work this out. Do you have something like Discord so we can communicate a bit faster?

**Comment by RuunArmee** [comment]
Yea, add me kristjan1889

**Comment by CodePanter** [comment]
We managed to resolve this issue. Some previous runelite update changed how profiles work, so we were able to find a version of the unlocks file in a different folder. Closing this issue now.
