### ISSUE TITLE
Buyable Grand Exchange Items (Locked)

### ISSUE THREAD

**Issue by RMFBronze** [CodePanter/another-bronzeman-mode#5]
![buyable item 1](https://user-images.githubusercontent.com/84482819/118899929-bb1bc100-b907-11eb-9438-cb2b982ce415.png)
So after the most previous update of runelite, i re-installed my plugins and done bronzeman as normal, but any different bronzeman plugin still allowed me to buy any items from the grand exchange which i had NOT unlocked yet.
If you are already aware of this, thats fine, but i had to let you know as im doing this for my progress stream and is very annoying checking my collection log everytime.

**Comment by CodePanter** [comment]
Thank you for reporting it! I was not aware of this, I will get on it!

**Comment by RMFBronze** [comment]
> Thank you for reporting it! I was not aware of this, I will get on it!

Glad to hear so! and by the way, bronzeman is fantastic, such a fun enjoyable way to play the game

**Comment by CodePanter** [comment]
Alright, the bug is fixed, and is up for review. With a bit of luck, it will be pushed to runelite soon!
And I completely agree with you, I don't even have a 'normal' account, I only play Bronzeman!

**Comment by RMFBronze** [comment]
> Alright, the bug is fixed, and is up for review. With a bit of luck, it will be pushed to runelite soon!
> And I completely agree with you, I don't even have a 'normal' account, I only play Bronzeman!

awesome! thankyou so much, and i know this is a longshot, but time on how soon?

**Comment by CodePanter** [comment]
The pull request has been accepted, so the update should be live now! https://github.com/runelite/plugin-hub/pull/1446#event-4776582516
Thanks again for reporting it, I haven't been playing much lately, so I missed this problem completely!
